languageCode = "en"
languageName = "English"
weight = 1
title = "Horseman "

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  # logo = "img/logo.png"
  description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"
  dateFormat = "2 January 2006"

[params.author]
  name = "Horse 0.0"
  image = "img/horseman.png"
  headline = ""
  bio = "A little bit about you"
   links = [
     { link = "https://nunocoracao.github.io/blowfish/" },
     { github = "https://github.com/horse-ma00" },
     { instagram = "https://instagram.com/matthew_ma.1" }
   ]
